name: fleetflow-sk
region: nyc
services:
  - name: fleetflow-sk
    source_dir: /
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 3000
    build_command: npm run build
    run_command: node node_modules/.bin/next start -p 3000
    github:
      branch: main
      deploy_on_push: true
      repo: fleetflow-sk
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "3000"
        scope: RUN_AND_BUILD_TIME
      - key: NEXTAUTH_URL
        value: https://fleetflowapp.com
        scope: RUN_AND_BUILD_TIME
      - key: NEXTAUTH_SECRET
        value: kPW2rGwLljJyGd2RK72wJvUPqK9BpiAcubHlMwjAKCY=
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SQUARE_APPLICATION_ID
        value: sq0idp-5GklzNdvq_BqP1gSCYAudA
        scope: RUN_AND_BUILD_TIME
      - key: SQUARE_ACCESS_TOKEN
        value: EAAAlwP5R9qoFiXV1dNd-4oNmMLVEb5Zw0-OPFd0fvMdAzOVbDL3LSe1aQq2Rmqb
        scope: RUN_AND_BUILD_TIME
      - key: SQUARE_ENVIRONMENT
        value: sandbox
        scope: RUN_AND_BUILD_TIME
      - key: SQUARE_LOCATION_ID
        value: MAIN
        scope: RUN_AND_BUILD_TIME
      - key: TWILIO_ACCOUNT_SID
        value: AC2e547d7c5d39dc8735c7bdb5546ded25
        scope: RUN_AND_BUILD_TIME
      - key: TWILIO_AUTH_TOKEN
        value: 4cda06498e86cc8f150d81e4e48b2aed
        scope: RUN_AND_BUILD_TIME
      - key: TWILIO_PHONE_NUMBER
        value: "+18333863509"
        scope: RUN_AND_BUILD_TIME
      - key: FMCSA_API_KEY
        value: 7de24c4a0eade12f34685829289e0446daf7880e
        scope: RUN_AND_BUILD_TIME
domains:
  - domain: fleetflowapp.com
    type: PRIMARY
  - domain: www.fleetflowapp.com
    type: ALIAS
