'use client';

import { useEffect, useState } from 'react';
import CarrierInvitationService, { CarrierInvitation, InvitationAnalytics } from '../services/CarrierInvitationService';

interface CarrierInvitationManagerProps {
  currentUser: {
    name: string;
    role: string;
    company: string;
  };
}

export default function CarrierInvitationManager({ currentUser }: CarrierInvitationManagerProps) {
  const [activeTab, setActiveTab] = useState<'send' | 'track' | 'analytics' | 'templates'>('send');
  const [invitations, setInvitations] = useState<CarrierInvitation[]>([]);
  const [analytics, setAnalytics] = useState<InvitationAnalytics | null>(null);
  const [loading, setLoading] = useState(false);

  // Send invitation form state
  const [invitationForm, setInvitationForm] = useState({
    carrierName: '',
    contactName: '',
    email: '',
    phone: '',
    mcNumber: '',
    dotNumber: '',
    invitationType: 'email' as 'email' | 'sms',
    customMessage: '',
    priority: 'standard' as 'standard' | 'high' | 'urgent',
    incentives: [] as string[],
  });

  const invitationService = CarrierInvitationService.getInstance();

  useEffect(() => {
    loadInvitations();
    loadAnalytics();
  }, []);

  const loadInvitations = () => {
    const allInvitations = invitationService.getAllInvitations();
    setInvitations(allInvitations);
  };

  const loadAnalytics = () => {
    const analyticsData = invitationService.getInvitationAnalytics();
    setAnalytics(analyticsData);
  };

  const handleSendInvitation = async () => {
    if (!invitationForm.email || !invitationForm.carrierName) {
      alert('Please fill in required fields (Carrier Name and Email)');
      return;
    }

    setLoading(true);

    try {
      const invitation = invitationService.createInvitation({
        invitedBy: currentUser.name,
        invitedByRole: currentUser.role,
        inviterCompany: currentUser.company,
        targetCarrier: {
          companyName: invitationForm.carrierName,
          contactName: invitationForm.contactName,
          email: invitationForm.email,
          phone: invitationForm.phone,
          mcNumber: invitationForm.mcNumber,
          dotNumber: invitationForm.dotNumber,
        },
        invitationType: invitationForm.invitationType,
        customMessage: invitationForm.customMessage,
        source: 'enhanced_portal',
        metadata: {
          prefilledData: {
            mcNumber: invitationForm.mcNumber,
            dotNumber: invitationForm.dotNumber,
          },
          incentives: invitationForm.incentives,
          priority: invitationForm.priority,
          referralCode: '', // Will be generated by service
        },
      });

      const result = await invitationService.sendInvitation(invitation);
      
      if (result.success) {
        alert('Invitation sent successfully!');
        // Reset form
        setInvitationForm({
          carrierName: '',
          contactName: '',
          email: '',
          phone: '',
          mcNumber: '',
          dotNumber: '',
          invitationType: 'email',
          customMessage: '',
          priority: 'standard',
          incentives: [],
        });
        loadInvitations();
        loadAnalytics();
      } else {
        alert(`Failed to send invitation: ${result.message}`);
      }
    } catch (error) {
      alert('Error sending invitation. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status: CarrierInvitation['status']) => {
    switch (status) {
      case 'completed': return '#10b981';
      case 'started': return '#3b82f6';
      case 'opened': return '#f59e0b';
      case 'sent': return '#6b7280';
      case 'expired': return '#ef4444';
      case 'declined': return '#ef4444';
      default: return '#6b7280';
    }
  };

  const getStatusIcon = (status: CarrierInvitation['status']) => {
    switch (status) {
      case 'completed': return '✅';
      case 'started': return '🚀';
      case 'opened': return '👀';
      case 'sent': return '📧';
      case 'expired': return '⏰';
      case 'declined': return '❌';
      default: return '📧';
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <div
      style={{
        background: 'rgba(0,0,0,0.6)',
        borderRadius: '20px',
        padding: '32px',
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: '32px' }}>
        <h2
          style={{
            color: 'white',
            fontSize: '28px',
            fontWeight: 'bold',
            marginBottom: '8px',
          }}
        >
          📧 Carrier Invitation Manager
        </h2>
        <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px' }}>
          Send invitations, track responses, and analyze conversion rates
        </p>
      </div>

      {/* Tab Navigation */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '32px' }}>
        {[
          { id: 'send', label: 'Send Invitations', icon: '📧' },
          { id: 'track', label: 'Track Invitations', icon: '📊' },
          { id: 'analytics', label: 'Analytics', icon: '📈' },
          { id: 'templates', label: 'Templates', icon: '📝' },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            style={{
              padding: '16px 20px',
              borderRadius: '12px',
              fontSize: '14px',
              fontWeight: '600',
              cursor: 'pointer',
              transition: 'all 0.3s ease',
              background:
                activeTab === tab.id
                  ? 'linear-gradient(135deg, #14b8a6, #0d9488)'
                  : 'rgba(255, 255, 255, 0.15)',
              color: 'white',
              backdropFilter: 'blur(10px)',
              border:
                activeTab === tab.id
                  ? 'none'
                  : '1px solid rgba(255, 255, 255, 0.2)',
              transform:
                activeTab === tab.id ? 'translateY(-2px)' : 'translateY(0)',
              boxShadow:
                activeTab === tab.id ? '0 8px 25px rgba(0, 0, 0, 0.3)' : 'none',
            }}
          >
            {tab.icon} {tab.label}
          </button>
        ))}
      </div>

      {/* Send Invitations Tab */}
      {activeTab === 'send' && (
        <div>
          <div
            style={{
              background: 'rgba(255,255,255,0.15)',
              backdropFilter: 'blur(10px)',
              borderRadius: '20px',
              padding: '32px',
              border: '1px solid rgba(255,255,255,0.2)',
            }}
          >
            <h3 style={{ color: 'white', fontSize: '20px', marginBottom: '24px' }}>
              📧 Send New Invitation
            </h3>

            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
                gap: '20px',
                marginBottom: '24px',
              }}
            >
              {/* Carrier Information */}
              <div>
                <h4 style={{ color: 'white', fontSize: '16px', marginBottom: '16px' }}>
                  Carrier Information
                </h4>
                
                <div style={{ marginBottom: '16px' }}>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Carrier Name *
                  </label>
                  <input
                    type="text"
                    value={invitationForm.carrierName}
                    onChange={(e) => setInvitationForm({...invitationForm, carrierName: e.target.value})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                    placeholder="Enter carrier company name"
                  />
                </div>

                <div style={{ marginBottom: '16px' }}>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Contact Name
                  </label>
                  <input
                    type="text"
                    value={invitationForm.contactName}
                    onChange={(e) => setInvitationForm({...invitationForm, contactName: e.target.value})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                    placeholder="Contact person name"
                  />
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                  <div>
                    <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                      MC Number
                    </label>
                    <input
                      type="text"
                      value={invitationForm.mcNumber}
                      onChange={(e) => setInvitationForm({...invitationForm, mcNumber: e.target.value})}
                      style={{
                        width: '100%',
                        padding: '12px',
                        borderRadius: '8px',
                        border: '1px solid rgba(255,255,255,0.3)',
                        background: 'rgba(255,255,255,0.1)',
                        color: 'white',
                        fontSize: '14px',
                      }}
                      placeholder="MC-123456"
                    />
                  </div>
                  <div>
                    <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                      DOT Number
                    </label>
                    <input
                      type="text"
                      value={invitationForm.dotNumber}
                      onChange={(e) => setInvitationForm({...invitationForm, dotNumber: e.target.value})}
                      style={{
                        width: '100%',
                        padding: '12px',
                        borderRadius: '8px',
                        border: '1px solid rgba(255,255,255,0.3)',
                        background: 'rgba(255,255,255,0.1)',
                        color: 'white',
                        fontSize: '14px',
                      }}
                      placeholder="DOT-789012"
                    />
                  </div>
                </div>
              </div>

              {/* Contact Information */}
              <div>
                <h4 style={{ color: 'white', fontSize: '16px', marginBottom: '16px' }}>
                  Contact Information
                </h4>
                
                <div style={{ marginBottom: '16px' }}>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Email Address *
                  </label>
                  <input
                    type="email"
                    value={invitationForm.email}
                    onChange={(e) => setInvitationForm({...invitationForm, email: e.target.value})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                    placeholder="contact@carrier.com"
                  />
                </div>

                <div style={{ marginBottom: '16px' }}>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Phone Number
                  </label>
                  <input
                    type="tel"
                    value={invitationForm.phone}
                    onChange={(e) => setInvitationForm({...invitationForm, phone: e.target.value})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                    placeholder="(555) 123-4567"
                  />
                </div>

                <div style={{ marginBottom: '16px' }}>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Invitation Type
                  </label>
                  <select
                    value={invitationForm.invitationType}
                    onChange={(e) => setInvitationForm({...invitationForm, invitationType: e.target.value as 'email' | 'sms'})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                  >
                    <option value="email">📧 Email Invitation</option>
                    <option value="sms">📱 SMS Invitation</option>
                  </select>
                </div>

                <div>
                  <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                    Priority
                  </label>
                  <select
                    value={invitationForm.priority}
                    onChange={(e) => setInvitationForm({...invitationForm, priority: e.target.value as any})}
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255,255,255,0.3)',
                      background: 'rgba(255,255,255,0.1)',
                      color: 'white',
                      fontSize: '14px',
                    }}
                  >
                    <option value="standard">Standard Priority</option>
                    <option value="high">High Priority</option>
                    <option value="urgent">Urgent Priority</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Custom Message */}
            <div style={{ marginBottom: '24px' }}>
              <label style={{ color: 'white', fontSize: '14px', display: 'block', marginBottom: '8px' }}>
                Custom Message (Optional)
              </label>
              <textarea
                value={invitationForm.customMessage}
                onChange={(e) => setInvitationForm({...invitationForm, customMessage: e.target.value})}
                style={{
                  width: '100%',
                  padding: '12px',
                  borderRadius: '8px',
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.1)',
                  color: 'white',
                  fontSize: '14px',
                  minHeight: '80px',
                  resize: 'vertical',
                }}
                placeholder="Add a personalized message to the invitation..."
              />
            </div>

            {/* Send Button */}
            <div style={{ textAlign: 'center' }}>
              <button
                onClick={handleSendInvitation}
                disabled={loading}
                style={{
                  background: loading 
                    ? 'rgba(107,114,128,0.5)' 
                    : 'linear-gradient(135deg, #14b8a6, #0d9488)',
                  color: 'white',
                  border: 'none',
                  padding: '16px 32px',
                  borderRadius: '12px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: loading ? 'not-allowed' : 'pointer',
                  transition: 'all 0.3s ease',
                }}
              >
                {loading ? '📤 Sending...' : '📧 Send Invitation'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Track Invitations Tab */}
      {activeTab === 'track' && (
        <div>
          <h3 style={{ color: 'white', fontSize: '20px', marginBottom: '24px' }}>
            📊 Invitation Tracking
          </h3>

          {/* Invitation Status Overview */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '16px',
              marginBottom: '24px',
            }}
          >
            {[
              { status: 'sent', label: 'Sent', count: invitations.filter(i => i.status === 'sent').length, color: '#6b7280' },
              { status: 'opened', label: 'Opened', count: invitations.filter(i => i.status === 'opened').length, color: '#f59e0b' },
              { status: 'started', label: 'Started', count: invitations.filter(i => i.status === 'started').length, color: '#3b82f6' },
              { status: 'completed', label: 'Completed', count: invitations.filter(i => i.status === 'completed').length, color: '#10b981' },
            ].map((stat, index) => (
              <div
                key={index}
                style={{
                  background: 'rgba(255,255,255,0.15)',
                  backdropFilter: 'blur(10px)',
                  borderRadius: '16px',
                  padding: '20px',
                  textAlign: 'center',
                  border: '1px solid rgba(255,255,255,0.2)',
                }}
              >
                <div style={{ color: stat.color, fontSize: '32px', fontWeight: 'bold', marginBottom: '8px' }}>
                  {stat.count}
                </div>
                <div style={{ color: 'white', fontSize: '16px', fontWeight: '600' }}>
                  {stat.label}
                </div>
              </div>
            ))}
          </div>

          {/* Invitations List */}
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '16px',
              padding: '24px',
            }}
          >
            <h4 style={{ color: 'white', fontSize: '18px', marginBottom: '16px' }}>
              Recent Invitations
            </h4>

            <div style={{ display: 'grid', gap: '12px' }}>
              {invitations.slice(0, 10).map((invitation) => (
                <div
                  key={invitation.id}
                  style={{
                    background: 'rgba(255,255,255,0.1)',
                    borderRadius: '12px',
                    padding: '16px',
                    display: 'grid',
                    gridTemplateColumns: '2fr 1fr 1fr 1fr 120px',
                    gap: '16px',
                    alignItems: 'center',
                  }}
                >
                  <div>
                    <div style={{ color: 'white', fontSize: '14px', fontWeight: 'bold', marginBottom: '4px' }}>
                      {invitation.targetCarrier.companyName}
                    </div>
                    <div style={{ color: 'rgba(255,255,255,0.7)', fontSize: '12px' }}>
                      {invitation.targetCarrier.email}
                    </div>
                  </div>
                  
                  <div style={{ color: 'rgba(255,255,255,0.8)', fontSize: '12px' }}>
                    {invitation.invitedBy}
                  </div>
                  
                  <div style={{ color: 'rgba(255,255,255,0.8)', fontSize: '12px' }}>
                    {formatDate(invitation.sentDate)}
                  </div>
                  
                  <div style={{ color: 'rgba(255,255,255,0.8)', fontSize: '12px' }}>
                    {invitation.invitationType}
                  </div>
                  
                  <div style={{ textAlign: 'center' }}>
                    <span
                      style={{
                        background: getStatusColor(invitation.status),
                        color: 'white',
                        padding: '4px 12px',
                        borderRadius: '20px',
                        fontSize: '11px',
                        fontWeight: 'bold',
                        textTransform: 'uppercase',
                      }}
                    >
                      {getStatusIcon(invitation.status)} {invitation.status}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Analytics Tab */}
      {activeTab === 'analytics' && analytics && (
        <div>
          <h3 style={{ color: 'white', fontSize: '20px', marginBottom: '24px' }}>
            📈 Invitation Analytics
          </h3>

          {/* Analytics Overview */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
              gap: '20px',
              marginBottom: '32px',
            }}
          >
            <div
              style={{
                background: 'rgba(255,255,255,0.15)',
                backdropFilter: 'blur(10px)',
                borderRadius: '16px',
                padding: '24px',
                textAlign: 'center',
              }}
            >
              <div style={{ color: '#10b981', fontSize: '36px', fontWeight: 'bold', marginBottom: '8px' }}>
                {analytics.conversionRate.toFixed(1)}%
              </div>
              <div style={{ color: 'white', fontSize: '16px', fontWeight: '600' }}>
                Conversion Rate
              </div>
            </div>

            <div
              style={{
                background: 'rgba(255,255,255,0.15)',
                backdropFilter: 'blur(10px)',
                borderRadius: '16px',
                padding: '24px',
                textAlign: 'center',
              }}
            >
              <div style={{ color: '#3b82f6', fontSize: '36px', fontWeight: 'bold', marginBottom: '8px' }}>
                {Math.round(analytics.averageTimeToComplete)}h
              </div>
              <div style={{ color: 'white', fontSize: '16px', fontWeight: '600' }}>
                Avg. Time to Complete
              </div>
            </div>

            <div
              style={{
                background: 'rgba(255,255,255,0.15)',
                backdropFilter: 'blur(10px)',
                borderRadius: '16px',
                padding: '24px',
                textAlign: 'center',
              }}
            >
              <div style={{ color: '#f59e0b', fontSize: '36px', fontWeight: 'bold', marginBottom: '8px' }}>
                {analytics.totalSent}
              </div>
              <div style={{ color: 'white', fontSize: '16px', fontWeight: '600' }}>
                Total Invitations Sent
              </div>
            </div>
          </div>

          {/* Top Performing Sources */}
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '16px',
              padding: '24px',
            }}
          >
            <h4 style={{ color: 'white', fontSize: '18px', marginBottom: '16px' }}>
              📊 Top Performing Sources
            </h4>
            
            <div style={{ display: 'grid', gap: '12px' }}>
              {analytics.topPerformingSources.map((source, index) => (
                <div
                  key={index}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '12px',
                    background: 'rgba(255,255,255,0.1)',
                    borderRadius: '8px',
                  }}
                >
                  <span style={{ color: 'white', fontSize: '14px', fontWeight: '600' }}>
                    {source.source.replace('_', ' ').toUpperCase()}
                  </span>
                  <span style={{ color: '#10b981', fontSize: '14px', fontWeight: 'bold' }}>
                    {source.completionRate.toFixed(1)}%
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Templates Tab */}
      {activeTab === 'templates' && (
        <div>
          <h3 style={{ color: 'white', fontSize: '20px', marginBottom: '24px' }}>
            📝 Invitation Templates
          </h3>
          
          <div style={{ textAlign: 'center', color: 'rgba(255,255,255,0.7)', fontSize: '16px' }}>
            <p>📧 Template management coming soon</p>
            <p>Currently using default email and SMS templates</p>
          </div>
        </div>
      )}
    </div>
  );
}
