name: fleetflow-sk
region: nyc
services:
  - name: fleetflow-sk
    run_command: npm start
    build_command: npm install && npm run build
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    github:
      repo: DEEDAVISINC/FLEETFLOW-SK
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "3000"
        scope: RUN_AND_BUILD_TIME
